#ifndef DIALOG_HPP_INCLUDED
#define DIALOG_HPP_INCLUDED

#define DIALOG_REGISTER 0
#define DIALOG_LOGIN 1
#define DIALOG_INVENTORY 2
#define DIALOG_STORE 3

#define DIALOG_HOUSE_STORAGE_VIEW 4
#define DIALOG_HOUSE_STORAGE_STORE 5
#define DIALOG_HOUSE_STORAGE_TAKE 6
#define DIALOG_HOUSE_STORAGE_STORE_AMOUNT 7
#define DIALOG_HOUSE_STORAGE_TAKE_AMOUNT 8

#endif
