#ifndef DIALOG_HPP_INCLUDED
#define DIALOG_HPP_INCLUDED

enum DialogID {
  DIALOG_REGISTER,
  DIALOG_LOGIN,
  DIALOG_INVENTORY,
  DIALOG_STORE,
  DIALOG_HOUSE_STORAGE_VIEW,
  DIALOG_HOUSE_STORAGE_STORE,
  DIALOG_HOUSE_STORAGE_TAKE,
  DIALOG_HOUSE_STORAGE_STORE_AMOUNT,
  DIALOG_HOUSE_STORAGE_TAKE_AMOUNT,
  DIALOG_GIVE,
  DIALOG_GIVE_AMOUNT
};

#endif
