#ifndef LIMITS_HPP_INCLUDED
#define LIMITS_HPP_INCLUDED

#define MAX_MISSION_CHECKPOINTS 256
#define MAX_RENTVEH 256
#define MAX_BUSINESSES 256
#define MAX_BUILDING_OBJECTS 1024
#define MAX_TEXT_LABELS 1024

#define MAX_HOUSES 1024
#define MAX_HOUSE_INVENTORY 64

#define MAX_STORE_INVENTORY 8

#define MAX_PLAYER_INVENTORY 8
#define MAX_PLAYER_POINTS 256
#define MAX_PLAYER_BUSINESSES 3
#define MAX_PLAYER_HOUSES 2
#define MAX_PLAYER_VEHICLES 8

#define WORLD_BUSINESS 1000
#define WORLD_HOUSE 10000

#endif
